### 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.



In [1]:
import numpy as np
import pandas as pd
from scipy.stats import norm

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
print(zp)
print(ks)

[ 35  45 190 200  40  70  54 150 120 110]
[401 574 874 919 459 739 653 902 746 832]


In [3]:
#Найдите ковариацию этих двух величин с помощью элементарных действий

In [4]:
cov = np.mean(zp * ks) - np.mean(zp) * np.mean(ks)
cov

9157.839999999997

In [5]:
#Ковариация с помощью функции cov из numpy

In [6]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Коэффициент корреляции Пирсона рассчитываем по формуле:

$$r_{XY} = \frac{cov_{XY}}{\sigma_{X}\sigma_{Y}}$$
Для этого находим стандратное отклонение sigma двух генеральных совокупностей:

In [7]:
sigma_zp =  (np.sqrt(((zp - zp.sum() / len(zp))**2).sum() / len(zp)))
sigma_ks =  (np.sqrt(((ks - ks.sum() / len(ks))**2).sum() / len(ks)))
print(sigma_zp)
print(sigma_ks)

59.115480206118605
174.55340157098058


In [8]:
#Проверяем правильность вычислений

In [9]:
sigma_zp_= zp.std(ddof=0)
sigma_ks_ = ks.std(ddof=0)
print(sigma_zp_)
print(sigma_ks_)

59.115480206118605
174.55340157098058


In [10]:
#Подставляем полученные значения в формулу и вычисляем коэффициент корреляции Пирсона:

In [11]:
r = cov / (sigma_zp * sigma_ks)
r

0.8874900920739158

Найдём коэффициент корреляции Пирсона с помощью функции NumPy и Pandas.

In [12]:
r = np.corrcoef(zp, ks)
r

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Коэффициенты корреляции совпадают.

### 2. Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
### Известно, что в генеральной совокупности IQ распределен нормально.
### Найдите доверительный интервал для математического ожидания с надежностью 0.95.



In [13]:
# Сигмы нет => критерий Стюдента 
# mean +- t(alpha/2) * sigma / sqrt(n)
arr = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
mean_arr = arr.mean()
alpha = 0.95
std_x = np.std(arr, ddof=1)
t = 2.262

left = mean_arr - t * std_x / np.sqrt(len(arr))
right = mean_arr + t * std_x / np.sqrt(len(arr))

print(f"Интервал: [{left:.2f};{right:.2f}]")

Интервал: [110.56;125.64]


### 3.Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.



In [14]:
D = 25
n = 27
X_ = 174.2
alpha = 0.05
t = 1.96

sigma =  np.sqrt(D)
T1 = X_ - t * sigma / (n ** 0.5)
T2 = X_ + t * sigma / (n ** 0.5)
print(f'Доверительный интервал имеет границы ({T1}, {T2})')

Доверительный интервал имеет границы (172.31398912064722, 176.08601087935276)
